version: '2'

services:
  web:
    image: dalareo/sspnginx
    hostname: localhost
    volumes_from:
      - php
    ports:
      - 80:80

  php:
    image: moss/selfservicepassword
    hostname: localhost
    environment:
      - LDAP_SERVER=
      - LDAP_STARTTLS=false
      - LDAP_BINDDN=
      - LDAP_BINDPASS=
      - LDAP_BASE_SEARCH=
      - LDAP_LOGIN_ATTRIBUTE=uid
      - LDAP_FULLNAME_ATTRIBUTE=cn
